receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4321  # Новый порт

exporters:
  otlp:
    endpoint: tempo:4317  # Порт Tempo остаётся 4317
    tls:
      insecure: true

processors:
  batch:
    timeout: 5s
    send_batch_size: 1024
    send_batch_max_size: 1024

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
